# Generated by Django 5.0.1 on 2024-02-02 00:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_item_amount_cents_alter_order_amount_cents'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expiration', models.IntegerField()),
                ('billing_data', models.JSONField()),
                ('currency', models.CharField(max_length=3)),
                ('integration_id', models.IntegerField()),
                ('lock_order_when_paid', models.BooleanField(default=False)),
                ('payment_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
