# Generated by Django 5.0.1 on 2024-02-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_cancel_payment_failure_payment_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cancel',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='payment',
            name='failure',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='payment',
            name='success',
            field=models.CharField(max_length=500),
        ),
    ]
