# Generated by Django 5.0.1 on 2024-02-02 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
