# Generated by Django 5.0.1 on 2024-02-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
    ]
