# Generated by Django 5.0.1 on 2024-02-02 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_webhookendpoint_is_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookendpoint',
            name='events',
        ),
    ]
