# Generated by Django 5.0.1 on 2024-01-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('total_transactions', models.IntegerField()),
                ('successful_transactions', models.IntegerField()),
                ('failed_transactions', models.IntegerField()),
                ('pending_transactions', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue_by_currency', models.JSONField()),
                ('average_transaction_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_customers', models.IntegerField()),
                ('total_customers', models.IntegerField()),
                ('total_refunds', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Performance Report',
                'verbose_name_plural': 'Performance Reports',
            },
        ),
        migrations.CreateModel(
            name='TransactionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('payment_method', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('transaction_date', models.DateTimeField()),
                ('customer_id', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction Analytics',
                'verbose_name_plural': 'Transactions Analytics',
            },
        ),
    ]
