# Generated by Django 5.0.1 on 2024-01-31 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='ticket_id',
        ),
        migrations.RemoveField(
            model_name='ticketresponse',
            name='response_id',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='ticketresponse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
