# Generated by Django 5.0.1 on 2024-01-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_remove_supportticket_ticket_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
