# Generated by Django 5.0.1 on 2024-02-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_creditcard_encrypted_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='encrypted_card_number',
            field=models.CharField(max_length=100),
        ),
    ]
