# Generated by Django 5.0.1 on 2024-02-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_creditcard_encrypted_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='encrypted_card_number',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_cvv',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_number',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_expiry',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cardholder_name',
            field=models.CharField(max_length=500),
        ),
    ]
