# Generated by Django 5.0.1 on 2024-02-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_auth_token_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount_cents',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount cents'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_cents',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount cents'),
        ),
    ]
