# Generated by Django 5.0.1 on 2024-02-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_item_amount_cents_alter_order_amount_cents'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=500)),
                ('card_expiry', models.CharField(max_length=500)),
                ('cardholder_name', models.CharField(max_length=500)),
                ('card_cvv', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
