# Generated by Django 5.0.1 on 2024-02-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_testcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcard',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('cancel', 'cancel'), ('failure', 'PayPal')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
